name: xmax_sdk
description: >-
  Flutter SDK for integrating Xmax AI real-time interactive video generation
  and media storage into iOS and Android apps.
version: 1.0.1
homepage: https://platform.xmaxai.com/
repository: https://github.com/XingMai/XmaxSDK-Flutter
issue_tracker: https://github.com/XingMai/XmaxSDK-Flutter/issues

topics:
  - ai
  - realtime
  - video-generation

platforms:
  android:
  ios:

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.3
  tencentcloud_cos_sdk_plugin_nobeacon: ^1.2.9
  volc_engine_rtc: ^3.60.6

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
